language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jmedynska/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jmedynska/docker-react npm run test
